#include <stdio.h>
#include <stdbool.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/signal.h>
#include <unistd.h>
#include <signal.h>
#include <memory.h>
#include <semaphore.h>
#include <regex.h>
#include <time.h>
